apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: deploy-busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command:
        - sleep
        - "36000"
        name: dep-busybox
        imagePullPolicy: IfNotPresent